server:
  port: 9998

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  metrics:
    tags:
      service: ascend-weather-mcp
      version: "@project.version@"
    distribution:
      percentiles-histogram:
        mcp.tool.duration: true

spring:
  application:
    name: ascend-weather-mcp
  threads:
    virtual:
      enabled: true

  ai:
    mcp:
      server:
        enabled: true
        name: ascend-weather-mcp
        version: "@project.version@"
        type: ASYNC
        protocol: STREAMABLE
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false

logging:
  level:
    org.springframework.ai.mcp: INFO
