[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=Xvfb :99 -screen 0 1920x1080x24 -ac +extension GLX +render -noreset
priority=10
autorestart=true

[program:x11vnc]
command=x11vnc -display :99 -forever -nopw -listen 0.0.0.0 -xkb
priority=20
autorestart=true

[program:fluxbox]
command=fluxbox -display :99
priority=25
autorestart=true

[program:novnc]
command=websockify --web=/usr/share/novnc/ 7900 localhost:5900
priority=30
autorestart=true

[program:uvicorn]
command=uvicorn src.main:app --host 0.0.0.0 --port 7021
priority=40
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
