app:
  unstructured:
    base-url: "http://ascend-unstructured:9080"
  docling:
    base-url: "http://ascend-docling:7021"
  paddleocr:
    base-url: "http://ascend-paddle-ocr:7022"
  s3:
    endpoint: "http://ascend-minio:9070"
  memory:
    semantic:
      base-url: "http://ascend-openmemory:7020"

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ascend_ai
  data:
    redis:
      host: redis
  ai:
    vectorstore:
      qdrant:
        host: qdrant
