server:
  port: 9998

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: ascend-ai-weather-mcp
  threads:
    virtual:
      enabled: true

  ai:
    mcp:
      server:
        enabled: true
        name: ascend-ai-weather-mcp
        version: 0.0.1
        type: ASYNC
        protocol: STREAMABLE
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false

logging:
  level:
    org.springframework.ai.mcp: INFO
